CREATE DATABASE ChefMateDB;

CREATE TABLE Users (
  UserID INT PRIMARY KEY IDENTITY(1,1),
  FullName NVARCHAR(100) NOT NULL,
  Phone NVARCHAR(10) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  CreateAt DATETIME DEFAULT GETDATE()
);