CREATE DATABASE IF NOT EXISTS chefmate_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE chefmate_db;

CREATE TABLE IF NOT EXISTS Users (
  userId INT PRIMARY KEY AUTO_INCREMENT,
  fullName VARCHAR(100) NOT NULL,
  phone VARCHAR(15) NOT NULL UNIQUE,
  email VARCHAR(100) UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  followCount INT NOT NULL DEFAULT 0,
  recipeCount INT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Recipes (
  recipeId INT PRIMARY KEY AUTO_INCREMENT,
  recipeName VARCHAR(100) NOT NULL,
  image VARCHAR(1000) NOT NULL,
  likeQuantity INT NOT NULL DEFAULT 0,
  cookingTime VARCHAR(20) NOT NULL,
  ration INT NOT NULL,
  viewCount INT NOT NULL DEFAULT 0,
  userId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_recipes_user FOREIGN KEY (userId) REFERENCES Users(userId)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Tags (
  tagId INT PRIMARY KEY AUTO_INCREMENT,
  tagName VARCHAR(100) NOT NULL,
  UNIQUE KEY uq_tag_name (tagName)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS RecipesTags (
  rtId INT PRIMARY KEY AUTO_INCREMENT,
  recipeId INT NOT NULL,
  tagId INT NOT NULL,
  CONSTRAINT fk_recipes_tags_recipe FOREIGN KEY (recipeId) REFERENCES Recipes(recipeId)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_recipes_tags_tag FOREIGN KEY (tagId) REFERENCES Tags(tagId)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  UNIQUE KEY uq_recipe_tag (recipeId, tagId)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Ingredients (
  ingredientId INT PRIMARY KEY AUTO_INCREMENT,
  ingredientName VARCHAR(100) NOT NULL,
  UNIQUE KEY uq_ingredient_name (ingredientName)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS RecipesIngredients (
  riId INT PRIMARY KEY AUTO_INCREMENT,
  recipeId INT NOT NULL,
  ingredientId INT NOT NULL,
  weight INT NOT NULL,
  unit VARCHAR(20) NOT NULL,
  CONSTRAINT fk_recipe_ingredient_recipe FOREIGN KEY (recipeId) REFERENCES Recipes(recipeId)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_recipe_ingredient_ingredient FOREIGN KEY (ingredientId) REFERENCES Ingredients(ingredientId)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CookingSteps (
  csId INT PRIMARY KEY AUTO_INCREMENT,
  recipeId INT NOT NULL,
  indexStep INT NOT NULL,
  content TEXT NOT NULL,
  CONSTRAINT fk_cooking_steps_recipe FOREIGN KEY (recipeId) REFERENCES Recipes(recipeId)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS UsersLike (
  ulId INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  recipeId INT NOT NULL,
  CONSTRAINT fk_users_like_user FOREIGN KEY (userId) REFERENCES Users(userId)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_users_like_recipe FOREIGN KEY (recipeId) REFERENCES Recipes(recipeId)
    ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE KEY uq_users_like (userId, recipeId)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS UsersComment (
  ucId INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  recipeId INT NOT NULL,
  content TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_comment_user FOREIGN KEY (userId) REFERENCES Users(userId)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_users_comment_recipe FOREIGN KEY (recipeId) REFERENCES Recipes(recipeId)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;
